DROP TABLE IF EXISTS prozacto_user;

-- INSERT INTO USER VALUES(1,CURRENT_TIMESTAMP,0,false,CURRENT_TIMESTAMP,0, 20, 1234, 'a.c@x.y', 'shreyansh', 'abc', 2,' shreyansh');
-- INSERT INTO USER VALUES(2,CURRENT_TIMESTAMP,0,false,CURRENT_TIMESTAMP,0, 25, 9090, 'ac@x.com', 'vignesh', 'abc', 12,' vignesh');
-- INSERT INTO USER VALUES(3,CURRENT_TIMESTAMP,0,false,CURRENT_TIMESTAMP,0, 46, 9090, 'ac@x.com', 'piddu', 'abc', 12,' piddu');
--
-- INSERT INTO DOCTOR VALUES(1,CURRENT_TIMESTAMP,0,false,CURRENT_TIMESTAMP,0,'NUEROLOGIST','SURGEON',1);